name:  'Crate: Merge Main'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call_crate_cicd:
    uses: orgrinrt/cicd/.github/workflows/crate_ci.yml@main
    secrets:
      CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      GH_RELEASE_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
    with:
      profile: 'minimal'
      toolchain: 'stable'
      override: true
      deploy_cratesio: true
      force_build: false
      force_tests: false
      force_deploy: false
      auto_bump: true
      test_feature_sets: "test_suite_a, test_suite_b, test_suite_c"
